[build]
  command = ""          # site statique
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]


# Rediriger toutes les routes /guide/<slug> vers guide.html (SPA)
[[redirects]]
  from = "/guide/*"
  to = "/guide.html"
  status = 200

# (facultatif) si tu veux une page /admin/guide
[[redirects]]
  from = "/admin/guides/*"
  to = "/admin-guides.html"
  status = 200

# Check-in digital (SPA route)
[[redirects]]
  from = "/checkin/*"
  to = "/checkin.html"
  status = 200

# Admin check-in
[[redirects]]
  from = "/admin/checkin/*"
  to = "/admin-checkin.html"
  status = 200
